### ISSUE TITLE
Fix Read The Docs config file.

### ISSUE THREAD

**Issue by fedejaure** [fedejaure/cookiecutter-modern-pypackage#528]
## Expected Behavior
The read the docs build process should work correctly with the provided config file.

## Actual Behavior
The read the docs build process is broken due to improper configuration in the config file.

Fix `.readthedocs.yml`:
```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

formats: all

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```
